### ISSUE TITLE
Easy data access utils

### ISSUE THREAD

**Issue by wtgee** [panoptes/panoptes-utils#177]
> :warning: **NOTE** This Issue will evolve. 

We want to create a group of functions that will make it easy to access data on the panoptes network. These will serve as the primary data access method and other tools (e.g. the data explorer) should rely on these functions for consistency.

This should serve as the umbrella Issue for a few PRs that will build these features. This includes (list may change in the future):

* [x] Basic `get` function to fetch a FITS file by `image_id`. #178 
* [x] Basic `get` function to fetch observation details by `sequence_id`. #181
* [x] Basic `search` for observations with constraints for: #181 #181 
    * [x] Coordinates (RA/Dec)
    * [x] Time (i.e. `start_date` and `end_date`)
    * [x] Unit ID
    * [x] Status (from the pipeline)
* [x] Create a `download_images` helper function that can take a list of bucket_paths or public_urls and download them.
* [ ] Investigate/Support alternative output formats:
    * Plain text: (all of these are easily accessed from dataframe)
        * [x] JSON
        * [x] CSV
        * [x] [Parquet](https://parquet.apache.org/)
    * Images
        * [x] FITS
    * Dataframes
        * [x] pandas
        * [ ] [xarray](http://xarray.pydata.org/en/stable/)
        * [ ] [dask](https://dask.org/)
    * Other
        * [ ] Python generators
        * [x] [Param](https://param.holoviz.org/)
* [ ] Lightcurve/PICID support (TBD)

The `get` function will work directly with the id for the associated object. This could look something like:

```python
from panoptes.utils.images import fits as fits_utils
from panoptes.utils.data import get_data, search_data

# Fetch a FITS image.
image_id = 'PAN001_14d3bd_20200412T123402'
image = get_data(image_id=image_id)

# Now we have FITS we can work with
data = fits_utils.getdata(image)
header = fits_utils.getheader(image)
...
```

```python
# Observation fetch returns a DataFrame with metadata about the images.
sequence_id = 'PAN001_14d3bd_20200412T100947'
observation = get_data(sequence_id=sequence_id)
```

Search functions would take basic constraints:

```python
# Search for observations returns DataFrame with metadata about the observations.
observations = search_data(observatons=True,
                           ra_min=32, ra_max=40,
                           dec_min=45, dec_max=60,
                           start_date='2019-01-01',
                           end_date='2019-06-01',
                           unit_ids=['PAN001', 'PAN012'])
```

There are a number of known issues or details to be worked out. One basic example is how we should limit results (we don't want to return a dataframe with 10 million rows) and therefore how we should sort or prioritize some of the results.

#### Related tasks

* [ ] Clean up `panoptes.utils.data` namespace (#176 )
* [ ] Set up firestore emulaor (#179)

**Comment by wtgee** [comment]
I'm marking this Issue as complete for now since we have all of the basics of this done.  Further features/ideas/discussion should open separate Issue.
